import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Privacy",
  description: "Plain-language privacy policy. We collect almost nothing.",
};

export default function PrivacyPage() {
  return (
    <main className="min-h-screen bg-[#F5F9FC] py-16 px-4">
      <div className="max-w-2xl mx-auto">

        <nav className="mb-8 text-xs">
          <Link href="/" className="text-[#4A5A6E] hover:text-[#143352] transition-colors">
            ← Back to PromptDolphin
          </Link>
        </nav>

        <header className="mb-12">
          <p className="text-xs uppercase tracking-widest text-[#A67C3D] font-semibold mb-2">
            Privacy Policy
          </p>
          <h1 className="text-4xl font-serif text-[#0E1A2A] mb-3" style={{ fontFamily: 'ui-serif, Georgia, "EB Garamond", serif' }}>
            Plain language. One page.
          </h1>
          <p className="text-xs text-[#8FA6BC]">Last updated: 2026-07-12</p>
        </header>

        <article className="text-[#0E1A2A] leading-relaxed space-y-8">

          <section>
            <h2 className="text-xl font-serif text-[#143352] mb-2" style={{ fontFamily: 'ui-serif, Georgia, "EB Garamond", serif' }}>
              The short version
            </h2>
            <p className="text-sm">
              We collect almost nothing. Nothing you type into the prompt box ever
              leaves your browser. We do not see your tasks. We do not see your
              prompts. We cannot, by design.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-serif text-[#143352] mb-2" style={{ fontFamily: 'ui-serif, Georgia, "EB Garamond", serif' }}>
              What we do NOT collect
            </h2>
            <ul className="text-sm space-y-1 list-disc pl-5">
              <li>Anything you type into the prompt box</li>
              <li>Your generated prompts</li>
              <li>Your name, email, or employer</li>
              <li>Your browsing history on or off this site</li>
              <li>Your IP address (beyond standard ephemeral server logs)</li>
              <li>Any cross-site tracking data</li>
            </ul>
            <p className="text-sm mt-3">
              Enforced by our <code className="bg-[#E8EFF5] text-[#143352] px-1.5 py-0.5 rounded font-mono text-xs">connect-src 'self'</code> Content Security Policy header (no third-party servers can receive your data) and by the open-source engine that contains no transmission code for user content.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-serif text-[#143352] mb-2" style={{ fontFamily: 'ui-serif, Georgia, "EB Garamond", serif' }}>
              What we do collect
            </h2>
            <ul className="text-sm space-y-2 list-disc pl-5">
              <li>
                <strong className="text-[#143352]">Nothing, at the moment</strong> - the app currently runs no analytics of any kind. No page-view tracking, no cookies, no user ID, no content. The only server-side traces are the standard, short-lived hosting logs every website produces.
              </li>
              <li>
                <strong className="text-[#143352]">Language preference</strong> - your chosen UI language is saved in your browser's localStorage (key <code className="bg-[#E8EFF5] text-[#143352] px-1.5 py-0.5 rounded font-mono text-xs">pd_lang</code>). It never leaves your device. We cannot read it.
              </li>
            </ul>
            <p className="text-sm mt-3 text-[#4A5A6E]">
              If we ever add privacy-preserving aggregate analytics (for example self-hosted page-view counts), we will update this page first, and it will never include anything you type.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-serif text-[#143352] mb-2" style={{ fontFamily: 'ui-serif, Georgia, "EB Garamond", serif' }}>
              How your data is processed
            </h2>
            <p className="text-sm">
              All prompt assembly happens in your browser using client-side
              JavaScript. The output you copy was generated by string-template
              functions running in your own browser's RAM. It was never on our
              servers. It cannot be — the code that runs the assembly has no
              network transmission capability.
            </p>
            <p className="text-sm mt-3">
              You can verify this by opening browser DevTools (F12), going to the
              Network tab, and observing zero outbound requests when you click
              "Engineer this prompt." See <Link href="/trust" className="text-[#143352] underline">/trust</Link> for the full technical verification guide.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-serif text-[#143352] mb-2" style={{ fontFamily: 'ui-serif, Georgia, "EB Garamond", serif' }}>
              Data retention
            </h2>
            <ul className="text-sm space-y-1 list-disc pl-5">
              <li>Your prompt content: not stored. Lives in browser RAM until you close the tab.</li>
              <li>Language preference: stored only in your browser. Cleared when you clear browser data.</li>
              <li>Analytics: none collected, so nothing is retained.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-serif text-[#143352] mb-2" style={{ fontFamily: 'ui-serif, Georgia, "EB Garamond", serif' }}>
              Your rights
            </h2>
            <ul className="text-sm space-y-2 list-disc pl-5">
              <li>
                <strong className="text-[#143352]">EU / UK (GDPR):</strong> right to access, rectification, erasure, and data portability.
                For analytics data, we hold no information linked to your identity, so erasure is automatic.
              </li>
              <li>
                <strong className="text-[#143352]">California (CCPA):</strong> we do not sell or share personal information.
                We do not share personal information with third parties at all.
              </li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-serif text-[#143352] mb-2" style={{ fontFamily: 'ui-serif, Georgia, "EB Garamond", serif' }}>
              Contact
            </h2>
            <p className="text-sm">
              Privacy questions: <a href="mailto:privacy@promptdolphin.com" className="text-[#143352] underline">privacy@promptdolphin.com</a>
            </p>
            <p className="text-sm">
              Data controller: Robic Direct Inc.
            </p>
            <p className="text-sm">
              DPA available on request for enterprise customers — contact{" "}
              <a href="mailto:enterprise@promptdolphin.com" className="text-[#143352] underline">enterprise@promptdolphin.com</a>.
            </p>
          </section>

        </article>

        <footer className="text-center text-xs text-[#8FA6BC] py-8 mt-12 border-t border-[#C4D2E0]">
          <p>Robic Direct Inc. · <Link href="/trust" className="underline hover:text-[#143352]">Trust & Security</Link> · <Link href="/" className="underline hover:text-[#143352]">Home</Link></p>
        </footer>

      </div>
    </main>
  );
}
